### ISSUE TITLE
No content in PDF in VS Code

### ISSUE THREAD

**Issue by shinokada** [qdm12/latexdevcontainer#1] opened 2020-10-13 08:17 UTC
Thank you for the repo.

I followed your README instruction.
I set up for my project, adding .devcontainer/devcontainer.json and .devcontainer/docker-compose.ym. 
I open the command palette in Visual Studio Code (CTRL+SHIFT+P) and select Remote-Containers: Open Folder in Container... and chose my project directory.

I have Remote-Containers and LaTeX-Workshop installed.

I built and saved my tex doc it created a PDF but there is NO content.

My tex file:

```
\documentclass{article} 
\begin{document}
An Example document.

Updating tex from VS Code.

\end{document}
```

Terminal output:

> [WARNING] TZ environment variable not set, time might be wrong!
> Docker socket not owned by group IDs 1000, 102 or 976, changing its group to 1000
> 
> Base version: alpine-2020-09-13T09:12:41Z-b015a59
> Running as user vscode
> VS code server 1.50.0
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
> Docker server  | client 19.03.12
> Docker-Compose 1.26.2
> 
> TexLive release 2020
> tlmgr version 55369 (2020-06-01 02:32:00 +0200)
> Useful commands available:
>  * Update LaTex packages: tlmgr update --all
>  * Install a LaTex package:
>        tlmgr install packagename
>        texhash
>  * Install an OS package: sudo apk add packagename
> [powerlevel10k] fetching gitstatusd .. [ok]                                  
>  /workspace ▓▒░          

Do you have any ideas?

**Comment by shinokada** [comment] 2020-10-13 10:20
It works now.
I don't know why.
I changed the theme, open the PDF in a browser from LaTeX-Workshop.

**Comment by qdm12** [comment] 2020-10-13 12:11
@shinokada thanks for reporting the issue. I'll have a look if I can reproduce the issue. Also for the Docker socket error, do you mind running in the vscode terminal

```sh
ls -al /var/run/docker.sock
```

and send me the output? I'm curious why it cannot have access to the Docker socket, especially since I use this approach for a bunch of other development containers.

Thanks!

**Comment by shinokada** [comment] 2020-10-13 20:15
Here is the output:

```
 /workspace ▓▒░ ls -al /var/run/docker.sock
srwxr-xr-x    1 root     vscode           0 Oct 10 00:47 /var/run/docker.sock
```

**Comment by qdm12** [comment] 2020-10-14 02:29
Thanks for the output!

I believe this is using TexLive. Although funnily enough, I'm no Latex expert either.

Adding another one would not be trivial, but I'll try to move the container to use XeLaTex instead of TexLive & tlmgr, maybe their install/package manager is better than TexLive.0

**Comment by shinokada** [comment] 2020-10-14 03:27
I don't think you need to change it.
Why don't you add a section in the README about "How to change to another typesetting engine using Dockerfile".

**Comment by qdm12** [comment] 2020-10-14 19:41
Yes that's a good idea, let's keep the issue opened so I can get to it in the future.

I'll probably fix up the Docker build first and base it on debian instead of Alpine as tlmgr doesn't seem to support Alpine's musl anymore, so commands might be different once that's done.

**Comment by shinokada** [comment] 2020-10-14 20:15
I wonder how much the image size will increases if you use the debian instead of Alpine.

**Comment by shinokada** [comment] 2020-10-14 23:05
# Suggestion for your repo structure:

[Jupyter notebook](https://github.com/jupyter/docker-stacks) repo has different images depends on [users' needs](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html).

I thought LaTeX is a similar situation. You may use LaTeX for essay, writing, thesis, etc.
So maybe you can have the existing repo as the base-latexcontainer, then we can create our stack and make a pull request to your repo.

Users can select one stack for their work.

What do you think?

**Comment by qdm12** [comment] 2020-10-15 02:39
Yes I can make different docker tags with different latex engines (from different Dockerfiles I would say).

Anyway, let me fix the existing texlive build first 😄 And debian would probably increase the image size by about 50MB with the packages installed, not a big deal either.

**Comment by qdm12** [comment] 2020-10-17 16:27
Build is fixed, I'll try to fix the several issues you're opened now.

> I wonder how much the image size will increases if you use the debian instead of Alpine.

It was 393MB, it's now 485MB

If you don't mind, can you create another issue to use different typesetting engines please? So that I can close this issue and for clarity purposes. Thanks!

Also the docker error in the terminal should be fixed now.

**Comment by qdm12** [comment] 2020-10-17 19:41
See #5  

You might want to `docker pull qmcgaw/latexdevcontainer` to get the newer version and then `Rebuild and reopen container` in the VScode command palette. I'll add some doc in the readme on how to update it too.

**Closed by qdm12** 2020-10-17 19:41 UTC
